version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: conserjeria
      MYSQL_USER: conserjeria_admin
      MYSQL_PASSWORD: 48s#231248s
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  conserjeria_app:
    build: .
    container_name: consejeria_mariadb_cr
    ports:
      - "8080:7070"
    depends_on:
      - mariadb
    environment:
      DB_USERNAME: conserjeria_admin
      DB_PASSWORD: 48s#231248s
      DB_PLATFORM: mysql
      DB_DDL_MODE: dropCreate
      DB_NAME: conserjeria
      DB_URL: jdbc:mysql://mariadb:3306/conserjeria?useSSL=false&serverTimezone=UTC
    restart: unless-stopped

volumes:
  mariadb_data: