# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: true
    run: true
  debug:
    sql: true
    lazyload: true
  logging: all

# database configuration
datasource:
  db:
    username: ${DB_USERNAME:conserjeria_admin}
    password: ${DB_PASSWORD:79z#5RX&qq5z}
    platform: ${DB_PLATFORM:sqlite}
    ddlMode: ${DB_DDL_MODE:dropCreate}
    dbName: ${DB_NAME:conserjeria}
    url: ${DB_URL:jdbc:sqlite:conserjeria.db}